micronaut:
  application:
    name: gateway
    server:
        port: 8080
  security:
    enabled: true 
    endpoints:
      login:
        enabled: true
consul:
    client:
        registration: 
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
